(** A unique identifier for a client on the exchange.

    Client order IDs are chosen by the client *)

open! Core

type t [@@deriving sexp, bin_io, compare, equal, hash, string]

include Comparable.S with type t := t
include Hashable.S with type t := t

(** {2 Generation}

    Order IDs should only be generated by the matching engine. The
    [Generator] module encapsulates this to make it harder to accidentally
    create order IDs from arbitrary integers elsewhere in the code. *)

module Generator : sig
  (* type client_order_id := t DECIDE WHETHER TO KEEP LATER *)
  type t [@@deriving sexp_of]

  val create : int -> t
end

val to_int : t -> int
val of_int : int -> t
